### ISSUE TITLE
数据集samples_15k

### ISSUE THREAD

**Issue by zkcpku** [bojone/rerope#12]
请问苏神所用的数据集samples_15k.jsonl的来源是什么？

**Comment by bojone** [comment]
自己从CC这个数据集里边按长度筛选出来的

**Comment by zkcpku** [comment]
感谢苏神！
我们基于您的ReRoPE工作，正在完善一篇小文章[HiRoPE](https://arxiv.org/pdf/2403.19115v1)，非常有幸已被ACL2024接收，烦请指导！
