### ISSUE TITLE
Dataset of ReROPE eval

### ISSUE THREAD

**Issue by Madhu000** [bojone/rerope#13]
Hi I was going through a paper on the topic of length extrapolation on code models namely "**HiRoPE: Length Extrapolation for Code Models**" (https://arxiv.org/pdf/2403.19115v1). In this paper authors have mentioned about the ReROPE-eval dataset. Can you please help me to get the ReRoPE-eval dataset because I have not found any dataset in this repository.

**Comment by zkcpku** [comment]
Thank you!
I am the author behind the work titled "HiRoPE," which is currently a work in progress. 
The dataset utilized in our research was sourced from this repository, specifically the file named **samples_15k.jsonl**, along with the **eval_loss.py** script.
For the sake of brevity in our exposition, we have adopted the nomenclature of the second script to refer to the dataset, hence the term "ReRoPE-eval" as referenced in our paper.
I sincerely apologize for any confusion this may have caused. 

Our work has been significantly inspired by the _ReRoPE_ project, and we would like to extend our sincere acknowledgement to the author _bojone_.
