### ISSUE TITLE
<q_len=1> question

### ISSUE THREAD

**Issue by wzhcz8902** [bojone/rerope#15]
https://github.com/bojone/rerope/blob/3710a359ae0a80aad98312c9194898fb7312dcf3/rerope_patch.py#L68-L74

In line 71, can you explain why sin is negated? And also why does it have nothing to with window size?

**Comment by wzhcz8902** [comment]
figured

**Comment by zhenghuawang6** [comment]
I still do not understand it .
can you explain it more?
