### ISSUE TITLE
[BUG] relative position ids seems wrong

### ISSUE THREAD

**Issue by wzhcz8902** [bojone/rerope#17]
https://github.com/bojone/rerope/blob/3710a359ae0a80aad98312c9194898fb7312dcf3/rerope_patch.py#L70

should this be 
`position_ids = (position_ids[:, -1:] - position_ids).clip(max=window) ` with ":" behind `-1`, just like leaky-rerope?
https://github.com/bojone/rerope/blob/3710a359ae0a80aad98312c9194898fb7312dcf3/leaky_rerope_patch.py#L77

**Comment by wzhcz8902** [comment]
@bojone Can you comment on this question?

**Comment by bojone** [comment]
我平时测的是batch_size=1的case，应该是没区别的。不过严格来说应该确实要修改一下，已更正，感谢指出
